version: '3'
services:
  server:
    restart: unless-stopped
    build: .
    environment:
      AMPLITUDE_URL: http://echo
      NAIS_CLUSTER_NAME: local
      PORT: 4243
      INGRESSES_URL: http://data/ingresses.json
      PROJECT_KEYS_FILE: /secrets/project-keys.json
    ports:
      - '4243:4243'
    depends_on:
      - echo
      - data
    volumes:
      - ./secrets/:/secrets/
  echo:
    image: mendhak/http-https-echo
    ports:
      - '8484:80'
  data:
    build: ./ingresses
    ports:
      - '2525:80'

