
version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: "confluentinc/cp-zookeeper:5.4.1"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    container_name: kafka
    image: "confluentinc/cp-kafka:5.4.1"
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    restart: on-failure
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
    command: "sh -c '/etc/confluent/docker/run'"

  # kafka-ui:
  #     container_name: kafka-ui
  #     image: "obsidiandynamics/kafdrop"
  #     ports:
  #        - "9000:9000"
  #     environment:
  #       KAFKA_BROKERCONNECT: "kafka:9092"
  #       JVM_OPTS: "-Xms32M -Xmx64M"
  #       SERVER_SERVLET_CONTEXTPATH: "/"
  #     restart: on-failure
  #     depends_on:
  #       - zookeeper
  #       - kafka
