version: '3'
services:
  server:
    restart: unless-stopped
    build: .
    environment:
      AMPLITUDE_URL: http://echo-server
      PORT: 4243
    ports:
      - '4243:4243'
  echo-server:
    image: mendhak/http-https-echo
    ports:
      - '8484:80'
  data:
    build: ./ingresses
    ports:
      - '2424:80'

