version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: "zookeeper"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    container_name: kafka
    image: "wurstmeister/kafka"
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  preloader:
    build:
      dockerfile: ./Dockerfile.Preloader
    environment:
      KAFKA_BROKERS: kafka:9093
      KAFKA_INGRESS_TOPIC: dataplattform.ingress-topic-v2
    depends_on:
      - kafka
