version: '3'
services:
  server:
    restart: unless-stopped
    build: .
    environment:
      AMPLITUDE_URL: http://echo
      NAIS_CLUSTER_NAME: local
      PORT: 4243
      PROJECT_KEYS_FILE: /secrets/project-keys.json
      KAFKA_BROKERS: kafka:9093
      KAFKA_INGRESS_TOPIC: dataplattform.ingress-topic-v2
    ports:
      - '4243:4243'
    depends_on:
      - echo
    volumes:
      - ./secrets/:/secrets/
  echo:
    image: mendhak/http-https-echo
    ports:
      - '8484:80'
