version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: "confluentinc/cp-zookeeper:5.4.1"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    container_name: kafka
    image: "confluentinc/cp-kafka:5.4.1"
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    command: "sh -c '/etc/confluent/docker/run'"
