apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: {{team}}
  name: amplitude-proxy
  namespace: foreldrepenger
spec:
  accessPolicy:
    outbound:
      external:
        - host: api.amplitude.com
      rules : []
    inbound:
      rules:
        - application: istio-ingressgateway
          namespace: istio-system
  image: {{version}}
  port: 4242
  team: {{team}}
  liveness:
    path: /health/is-alive
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health/is-ready
    initialDelay: 10
    timeout: 1
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 100
  resources:
    limits:
      cpu: 500m
      memory: 64Mi
    requests:
      cpu: 200m
      memory: 32Mi
  ingresses:
    - "https://amplitude.nav.no"
  logformat: accesslog
  logtransform: dns_loglevel
  secrets:
    - name: amplitude-secrets
  env:
    - name: APP_VERSION
      value: {{version}}
    - name: AMPLITUDE_URL
      value: https://api.amplitude.com

