apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: team-researchops
  name: amplitude-proxy
  namespace: team-researchops
spec:
  accessPolicy:
    outbound:
      external:
        - host: api.eu.amplitude.com
        - host: cdn.amplitude.com
  image: {{image}}
  port: 4242
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-infrastructure
  liveness:
    path: /health/is-alive
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health/is-ready
    initialDelay: 10
    timeout: 1
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://amplitude.intern.dev.nav.no"
  env:
    - name: AMPLITUDE_URL
      value: https://api.eu.amplitude.com
    - name: KAFKA_INGRESS_TOPIC
      value: team-researchops.ingress-topic-v2
    - name: PROJECT_KEYS_FILE
      value: /var/run/secrets/project-keys.json
  filesFrom:
    - secret: amplitude-project-keys
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: amplitude-proxy-eu-networkpolicy
  namespace: team-researchops
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 3.64.0.0/12
        - ipBlock:
            cidr: 18.154.0.0/15
        - ipBlock:
            cidr: 18.156.0.0/14
        - ipBlock:
            cidr: 35.156.0.0/14
  podSelector:
    matchLabels:
      app: amplitude-proxy
  policyTypes:
    - Egress

