apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: dataplattform
  name: amplitude-proxy
  namespace: dataplattform
spec:
  accessPolicy:
    outbound:
      external:
        - host: api.amplitude.com
        - host: cdn.amplitude.com
      rules : []
    inbound:
      rules:
        - application: istio-ingressgateway
          namespace: istio-system
  image: {{image}}
  port: 4242
  liveness:
    path: /health/is-alive
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health/is-ready
    initialDelay: 10
    timeout: 1
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://amplitude.nav.no"
  logformat: accesslog
  logtransform: dns_loglevel
  env:
    - name: APP_VERSION
      value: {{image}}
    - name: AMPLITUDE_URL
      value: https://api.amplitude.com

