apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: dataplattform
  name: amplitude-proxy
  namespace: dataplattform
spec:
  accessPolicy:
    outbound:
      external:
        - host: api.amplitude.com
        - host: cdn.amplitude.com
      rules:
        - application: amplitude-data
          namespace: dataplattform
    inbound:
      rules:
        - application: istio-ingressgateway
          namespace: istio-system
  image: {{image}}
  port: 4242
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    path: /health/is-alive
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health/is-ready
    initialDelay: 10
    timeout: 1
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://amplitude.nav.no"
  env:
    - name: APP_VERSION
      value: {{image}}
    - name: AMPLITUDE_URL
      value: https://api.amplitude.com
    - name: INGRESSES_URL
      value: http://amplitude-data/ingresses.json
    - name: PROJECT_KEY_MAPPINGS
      value: "{\"55477baea93c5227d8c0f6b813653615\":\"*\"}"
