apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: dataplattform
  name: amplitude-data
  namespace: dataplattform
spec:
  accessPolicy:
    inbound:
      rules:
        - application: amplitude-proxy
          namespace: dataplattform
  image: IMAGE_NAME
  port: 80
  liveness:
    path: /
  readiness:
    path: /
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 24Mi
    requests:
      cpu: 50m
      memory: 12Mi

